--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/5/2024 3:33:21 PM
-- Server version: 8.4.0
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE luky;

--
-- Drop table `categorias`
--
DROP TABLE IF EXISTS categorias;

--
-- Drop table `comentarios`
--
DROP TABLE IF EXISTS comentarios;

--
-- Drop table `publicaciones`
--
DROP TABLE IF EXISTS publicaciones;

--
-- Drop table `usuarios`
--
DROP TABLE IF EXISTS usuarios;

--
-- Drop table `valoraciones`
--
DROP TABLE IF EXISTS valoraciones;

--
-- Set default database
--
USE luky;

--
-- Create table `valoraciones`
--
CREATE TABLE IF NOT EXISTS valoraciones (
  ID int NOT NULL AUTO_INCREMENT,
  publicacionID int NOT NULL,
  valorP double NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `usuarios`
--
CREATE TABLE IF NOT EXISTS usuarios (
  ID int NOT NULL AUTO_INCREMENT,
  idUser int NOT NULL,
  nombres varchar(50) NOT NULL,
  apellidoPaterno varchar(75) NOT NULL,
  apellidoMaterno varchar(75) NOT NULL,
  email varchar(50) NOT NULL,
  pass varchar(30) NOT NULL,
  telefono varchar(10) DEFAULT NULL,
  calificacion decimal(2, 1) NOT NULL DEFAULT 0.0,
  isTrabajador tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `publicaciones`
--
CREATE TABLE IF NOT EXISTS publicaciones (
  ID int NOT NULL AUTO_INCREMENT,
  iDPublicacion int NOT NULL,
  tituloP varchar(50) NOT NULL,
  fecha datetime NOT NULL,
  descripcion varchar(255) NOT NULL,
  precioT decimal(10, 2) DEFAULT 0.00,
  categoriaID smallint NOT NULL,
  usuarioID int NOT NULL,
  valoracion double NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `comentarios`
--
CREATE TABLE IF NOT EXISTS comentarios (
  ID int NOT NULL AUTO_INCREMENT,
  comentario varchar(255) NOT NULL,
  publicacionID int NOT NULL,
  usuarioID int NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `categorias`
--
CREATE TABLE IF NOT EXISTS categorias (
  ID int NOT NULL AUTO_INCREMENT,
  tipoCategoria varchar(50) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

-- Table luky.valoraciones does not contain any data (it is empty)

-- Table luky.usuarios does not contain any data (it is empty)

-- Table luky.publicaciones does not contain any data (it is empty)

-- Table luky.comentarios does not contain any data (it is empty)

-- Table luky.categorias does not contain any data (it is empty)

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;