--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/11/2024 12:01:14 AM
-- Server version: 8.4.0
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE luky;

--
-- Drop table `categorias`
--
DROP TABLE IF EXISTS categorias;

--
-- Drop table `comentarios`
--
DROP TABLE IF EXISTS comentarios;

--
-- Drop table `publicaciones`
--
DROP TABLE IF EXISTS publicaciones;

--
-- Drop table `usuarios`
--
DROP TABLE IF EXISTS usuarios;

--
-- Drop table `valoraciones`
--
DROP TABLE IF EXISTS valoraciones;

--
-- Set default database
--
USE luky;

--
-- Create table `valoraciones`
--
CREATE TABLE valoraciones (
  ID int NOT NULL AUTO_INCREMENT,
  publicacionID int NOT NULL,
  valorP double NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `usuarios`
--
CREATE TABLE usuarios (
  ID int NOT NULL,
  nombres varchar(50) NOT NULL,
  apellidoPaterno varchar(75) NOT NULL,
  apellidoMaterno varchar(75) NOT NULL,
  email varchar(50) NOT NULL,
  pass varchar(30) NOT NULL,
  telefono varchar(10) DEFAULT NULL,
  calificacion decimal(2, 1) NOT NULL DEFAULT 0.0,
  isTrabajador tinyint NOT NULL DEFAULT 0,
  fechaCreacion datetime DEFAULT (NOW()),
  fechaModif datetime DEFAULT (NOW()),
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `publicaciones`
--
CREATE TABLE publicaciones (
  ID int NOT NULL AUTO_INCREMENT,
  iDPublicacion int NOT NULL,
  tituloP varchar(50) NOT NULL,
  fecha datetime NOT NULL,
  descripcion varchar(255) NOT NULL,
  precioT decimal(10, 2) DEFAULT 0.00,
  categoriaID smallint NOT NULL,
  usuarioID int NOT NULL,
  valoracion double NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `comentarios`
--
CREATE TABLE comentarios (
  ID int NOT NULL AUTO_INCREMENT,
  comentario text NOT NULL,
  publicacionID int NOT NULL,
  usuarioID int NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `categorias`
--
CREATE TABLE categorias (
  ID int NOT NULL AUTO_INCREMENT,
  tipoCategoria varchar(50) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table valoraciones
--
INSERT INTO valoraciones VALUES
(1, 1, 4.3),
(2, 1, 3.2),
(3, 1, 4.7);

-- 
-- Dumping data for table usuarios
--
INSERT INTO usuarios VALUES
(1, 'DILAN ESAU', 'PALAFOX', 'MENDEZ', 'dilan.palafox.12@icloud.com', '1230', '2229072409', 5.0, 0, '2024-07-10 15:24:03', '2024-07-10 15:26:28');

-- 
-- Dumping data for table publicaciones
--
INSERT INTO publicaciones VALUES
(1, 1, 'Plomeria', '2024-07-09 15:49:55', 'Vendo mis servicios de plomeria', 25.46, 2, 1, 4.066666666666666);

-- Table luky.comentarios does not contain any data (it is empty)

-- 
-- Dumping data for table categorias
--
INSERT INTO categorias VALUES
(1, 'Plomeria'),
(2, 'Informatica'),
(3, 'Medicina'),
(4, 'Carpinteria');

--
-- Set default database
--
USE luky;

--
-- Drop trigger `actualizarValoracion`
--
DROP TRIGGER IF EXISTS actualizarValoracion;

--
-- Set default database
--
USE luky;

DELIMITER $$

--
-- Create trigger `actualizarValoracion`
--
CREATE
DEFINER = 'root'@'localhost'
TRIGGER actualizarValoracion
AFTER INSERT
ON valoraciones
FOR EACH ROW
BEGIN
  DECLARE sum_valoracion double;
  DECLARE count_valoracion double;

  SELECT
    SUM(v.valorP) INTO sum_valoracion
  FROM valoraciones v
  WHERE v.publicacionID = NEW.publicacionID;
  SELECT
    COUNT(*) INTO count_valoracion
  FROM valoraciones v
  WHERE v.publicacionID = NEW.publicacionID;


  UPDATE publicaciones p
  SET p.valoracion = sum_valoracion / count_valoracion
  WHERE p.iDPublicacion = NEW.publicacionID;

END
$$

DELIMITER ;

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;