--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/15/2024 4:34:09 PM
-- Server version: 8.4.0
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP DATABASE IF EXISTS luky;

CREATE DATABASE IF NOT EXISTS luky
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE luky;

--
-- Create table `usuarios`
--
CREATE TABLE IF NOT EXISTS usuarios (
  ID int NOT NULL AUTO_INCREMENT,
  nombres varchar(50) NOT NULL,
  apellidoPaterno varchar(75) NOT NULL,
  apellidoMaterno varchar(75) NOT NULL,
  email varchar(50) NOT NULL,
  pass varchar(255) NOT NULL,
  isTrabajador tinyint NOT NULL DEFAULT 0,
  fechaCreacion datetime DEFAULT (NOW()),
  fechaModif datetime DEFAULT (NOW()),
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `categorias`
--
CREATE TABLE IF NOT EXISTS categorias (
  ID int NOT NULL AUTO_INCREMENT,
  tipoCategoria varchar(50) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `publicaciones`
--
CREATE TABLE IF NOT EXISTS publicaciones (
  ID int NOT NULL AUTO_INCREMENT,
  tituloP varchar(50) NOT NULL,
  fecha datetime NOT NULL DEFAULT (NOW()),
  descripcion text NOT NULL,
  precioI decimal(10, 2) DEFAULT 0.00,
  precioF decimal(10, 2) DEFAULT 0.00,
  categoriaID int NOT NULL,
  usuarioID int NOT NULL,
  valoracion decimal(10, 2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE publicaciones
ADD CONSTRAINT FK_categoria FOREIGN KEY (categoriaID)
REFERENCES categorias (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE publicaciones
ADD CONSTRAINT FK_user FOREIGN KEY (usuarioID)
REFERENCES usuarios (ID) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `insertPublicacion`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE IF NOT EXISTS insertPublicacion (IN titulo varchar(75), IN descript text, IN precioIni decimal(10, 2), IN precioFin decimal(10, 2), IN catID smallint, IN userID int)
BEGIN
  INSERT INTO publicaciones (tituloP
  , fecha
  , descripcion
  , precioI
  , categoriaID
  , usuarioID
  , valoracion
  , precioF)
    VALUES (titulo -- tituloP - VARCHAR(50) NOT NULL
    , DEFAULT -- fecha - DATETIME NOT NULL
    , descript -- descripcion - TEXT NOT NULL
    , precioIni -- precioI - DECIMAL(10, 2)
    , catID -- categoriaID - SMALLINT NOT NULL
    , userID -- usuarioID - INT NOT NULL
    , DEFAULT -- valoracion - DECIMAL(10, 2) NOT NULL
    , precioFin -- precioF - DECIMAL(10, 2)
    );
END
$$

DELIMITER ;

--
-- Create table `valoraciones`
--
CREATE TABLE IF NOT EXISTS valoraciones (
  ID int NOT NULL AUTO_INCREMENT,
  publicacionID int NOT NULL,
  valorP double NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE valoraciones
ADD CONSTRAINT FK_public FOREIGN KEY (publicacionID)
REFERENCES publicaciones (ID) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `insertValoracion`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE IF NOT EXISTS insertValoracion (IN pubID int, IN valorV double)
BEGIN
  INSERT INTO valoraciones (publicacionID
  , valorP)
    VALUES (pubID -- publicacionID - INT NOT NULL
    , valorV -- valorP - DOUBLE NOT NULL
    );
END
$$

DELIMITER ;

--
-- Create table `comentarios`
--
CREATE TABLE IF NOT EXISTS comentarios (
  ID int NOT NULL AUTO_INCREMENT,
  comentario text NOT NULL,
  publicacionID int NOT NULL,
  usuarioID int NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table usuarios
--
INSERT INTO usuarios VALUES
(1, 'AXEL', 'SALINAS', 'ANTONIO', 'axel@gmail.com', '123', 0, '2024-07-15 16:17:53', '2024-07-15 16:17:53'),
(2, 'DAVID', 'PARRA', 'SANTIZO', 'david@gmail.com', '456', 0, '2024-07-15 16:19:22', '2024-07-15 16:19:22'),
(3, 'DILAN', 'PALAFOX', 'MENDEZ', 'dilan@gmail.com', '789', 0, '2024-07-15 16:19:39', '2024-07-15 16:19:39');

-- 
-- Dumping data for table categorias
--
INSERT INTO categorias VALUES
(1, 'INFORMATICA'),
(2, 'PLOMERIA'),
(3, 'CARPINTERIA'),
(4, 'CONTADURIA'),
(5, 'GASTRONOMIA'),
(6, 'EVENTOS'),
(7, 'ADMINISTRACION'),
(8, 'MEDICINA');

-- 
-- Dumping data for table publicaciones
--
INSERT INTO publicaciones VALUES
(1, 'Reparacion de Compuradoras', '2024-07-15 16:22:19', 'Se valoran y reparan computadoras a domicilio', 265.00, 0.00, 1, 1, 0.00),
(2, 'Servicio de plomeria', '2024-07-15 16:25:24', 'Se realizan trabajos de plomeria de cualquier tipo', 150.00, 600.00, 2, 3, 0.00),
(3, 'Limpieza de Computadoras', '2024-07-15 16:26:09', 'Se realiza limpieza profunda de laptops y computadoras', 120.00, 250.00, 1, 2, 0.00),
(4, 'Mantenimiento de impresoras', '2024-07-15 16:27:13', 'Se realiza el mantenimiento mensual a impresoras', 200.00, 500.00, 1, 1, 0.00);

-- Table luky.valoraciones does not contain any data (it is empty)

-- Table luky.comentarios does not contain any data (it is empty)

--
-- Set default database
--
USE luky;

DELIMITER $$

--
-- Create trigger `actualizarValoracion`
--
CREATE
DEFINER = 'root'@'localhost'
TRIGGER IF NOT EXISTS actualizarValoracion
AFTER INSERT
ON valoraciones
FOR EACH ROW
BEGIN
  DECLARE sum_valoracion double;
  DECLARE count_valoracion double;

  SELECT
    SUM(v.valorP) INTO sum_valoracion
  FROM valoraciones v
  WHERE v.publicacionID = NEW.publicacionID;
  SELECT
    COUNT(*) INTO count_valoracion
  FROM valoraciones v
  WHERE v.publicacionID = NEW.publicacionID;


  UPDATE publicaciones p
  SET p.valoracion = sum_valoracion / count_valoracion
  WHERE p.ID = NEW.publicacionID;

END
$$

DELIMITER ;

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;